### ISSUE TITLE
Gathered info and instructions for installation

### ISSUE THREAD

**Issue by mikaelsouza** [ywilke/auctionhistory#1]
Hello there!

I would like to know if you plan release the data you've gathered and if not, if you plan to write some instructions showing how to run your application.

Thanks!

**Comment by ywilke** [comment]
Hi!

I am currently not planning to release the raw data. You can click "Edit in Chart Studio" on the graph to see the data for that single item. Don't use this feature to try and scrape the whole database.
The automated scanning runs in a very hacky way and requires a lot of manual configuration and setup to make it work for different machines. I might write instructions if I manage to improve this.

**Comment by mikaelsouza** [comment]
Thanks for your response!

I won't try to scrap it and I hope you find some time to improve what is needed.

Thanks again!
